export const NOTIFICATION_TYPES = {
  OFFER_RECEIVED: "OFFER_RECEIVED",
  OFFER_ACCEPTED: "OFFER_ACCEPTED",
  OFFER_REJECTED: "OFFER_REJECTED",
  SWAP_COMPLETED: "SWAP_COMPLETED",
  SWAP_CANCELLED: "SWAP_CANCELLED",
};

export const NOTIFICATION_TITLES = {
  OFFER_RECEIVED: "New Offer Received",
  OFFER_ACCEPTED: "Offer Accepted",
  OFFER_REJECTED: "Offer Declined",
  SWAP_COMPLETED: "Swap Completed",
  SWAP_CANCELLED: "Swap Cancelled",
};